# Generated by Django 4.1.3 on 2022-12-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_user_id', models.CharField(default=None, max_length=30)),
                ('os_domain', models.URLField(max_length=100, null=True)),
                ('did', models.CharField(max_length=30, null=True)),
                ('wid', models.CharField(max_length=30, null=True)),
                ('eid', models.CharField(max_length=30, null=True)),
                ('access_token', models.CharField(max_length=100, null=True)),
                ('refresh_token', models.CharField(max_length=100, null=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('modelling', models.BooleanField(default=False)),
                ('last_start', models.DateTimeField(null=True)),
                ('completed', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_doc_id', models.CharField(default=None, max_length=40)),
                ('os_workspace_id', models.CharField(default=None, max_length=40)),
                ('os_element_id', models.CharField(default=None, max_length=40)),
                ('cad_drawing', models.TextField(null=True)),
                ('completion_count', models.PositiveIntegerField(default=0)),
                ('question_name', models.TextField(null=True)),
                ('difficulty', models.PositiveIntegerField(default=0)),
                ('thumbnail', models.TextField(null=True)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
