# Generated by Django 4.1.3 on 2022-12-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='cad_drawing',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_name',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
