# Generated by Django 4.1.7 on 2023-03-03 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questioner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_MSPS',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questioner.question')),
                ('is_multi_part', models.BooleanField(default=False, help_text='Does this question contains multiple parts in one Part Studio?')),
                ('starting_eid', models.CharField(blank=True, default=None, help_text='(Optional) Starting part studio that need to be imported to user document with derived features. Leave blank if none is required.', max_length=40, null=True, verbose_name='Starting element ID')),
                ('init_mid', models.CharField(default=None, help_text="Last microversion of the starting element's version", max_length=40, null=True)),
                ('total_steps', models.IntegerField(default=0, verbose_name='Number of steps')),
                ('completion_feature_cnt', models.JSONField(default=list, help_text='List of feature counts required by users in history')),
            ],
            options={
                'verbose_name': 'Multi-step Part Studio Question',
            },
            bases=('questioner.question',),
        ),
        migrations.AddField(
            model_name='authuser',
            name='curr_step',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_multi_step',
            field=models.BooleanField(default=False, help_text='Has multiple steps required for evaluation'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='curr_question_type',
            field=models.CharField(choices=[('UNKN', 'Unknown'), ('SPPS', 'Single-part Part Studio'), ('MPPS', 'Multi-part Part Studio'), ('ASMB', 'Assembly Mating'), ('MSPS', 'Multi-step Part Studio')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='jpeg_drawing_eid',
            field=models.CharField(help_text='Export a drawing as a JPEG to the questions document and input that element ID here. Portrait rather than landscape is preferred.', max_length=40, null=True, verbose_name='Onshape element ID of a JPEG export of a drawing'),
        ),
        migrations.AlterField(
            model_name='question',
            name='os_drawing_eid',
            field=models.CharField(help_text='Element ID of the Onshape drawing that users can open in a new tab.', max_length=40, null=True, verbose_name='Onshape element ID of the main Onshape drawing'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('UNKN', 'Unknown'), ('SPPS', 'Single-part Part Studio'), ('MPPS', 'Multi-part Part Studio'), ('ASMB', 'Assembly Mating'), ('MSPS', 'Multi-step Part Studio')], default='UNKN', max_length=4),
        ),
        migrations.AlterField(
            model_name='question_mpps',
            name='starting_eid',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Starting part studio that need to be imported to user document with derived features. Leave blank if none is required.', max_length=40, null=True, verbose_name='Starting element ID'),
        ),
        migrations.CreateModel(
            name='Question_Step_PS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(default=1)),
                ('eid', models.CharField(default=None, max_length=40, verbose_name='Onshape element ID')),
                ('mid', models.CharField(default=None, help_text="Last microversion of the reference element's version", max_length=40, null=True)),
                ('os_drawing_eid', models.CharField(max_length=40, null=True, verbose_name='Onshape drawing element ID of the step')),
                ('jpeg_drawing_eid', models.CharField(max_length=40, null=True, verbose_name='JPEG drawing element ID of the step')),
                ('drawing_jpeg', models.TextField(null=True)),
                ('additional_instructions', models.TextField(blank=True, default=None, help_text='(Opitonal) additional instructions for this step', null=True)),
                ('model_mass', models.JSONField(default=list, help_text='Mass in kg', null=True)),
                ('model_volume', models.JSONField(default=list, help_text='Volume in m^3', null=True)),
                ('model_SA', models.JSONField(default=list, help_text='Surface area in m^2', null=True)),
                ('model_inertia', models.JSONField(default=list, help_text='3 element array describing the Principal Interia', null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questioner.question_msps')),
            ],
            options={
                'verbose_name': 'MSPS Question Step',
            },
        ),
    ]
