# Generated by Django 4.1.3 on 2022-12-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='additional_instructions',
            field=models.TextField(blank=True, help_text='(Opitonal) additional instructions for users', null=True),
        ),
    ]
