# Generated by Django 4.1.3 on 2022-12-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='cad_drawing',
        ),
        migrations.RemoveField(
            model_name='question',
            name='os_element_id',
        ),
        migrations.AddField(
            model_name='question',
            name='drawing_jpeg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='os_drawing_element_id',
            field=models.CharField(help_text='Element ID of the Onshape drawing that users can open in a new tab', max_length=200, null=True, unique=True, verbose_name='Element ID of the main drawing'),
        ),
        migrations.AddField(
            model_name='question',
            name='os_drawing_jpeg_element_id',
            field=models.CharField(help_text='Export a drawing as a JPEG to the questions document and input that element ID here. Portrait rather than landscape is best.', max_length=200, null=True, unique=True, verbose_name='Element ID of a JPEG export of a drawing'),
        ),
        migrations.AddField(
            model_name='question',
            name='os_part_studio_id',
            field=models.CharField(default=None, help_text='Only relevant for initial save and model update', max_length=40, verbose_name='Element ID of derived Part Studio'),
        ),
    ]
