# Generated by Django 4.1.3 on 2022-12-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioner', '0002_alter_question_cad_drawing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='additional_instructions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='model_COM_x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='model_COM_y',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='model_COM_z',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='model_SA',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='model_mass',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='model_volume',
            field=models.FloatField(null=True),
        ),
    ]
