# Generated by Django 4.1.7 on 2023-03-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioner', '0002_question_msps_authuser_curr_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_collecting_data',
            field=models.BooleanField(default=False, help_text='User design data is only collected when this is set to be True'),
        ),
    ]
