# Generated by Django 4.1.3 on 2023-01-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioner', '0002_remove_question_cad_drawing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='end_microversion_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='completion_feature_cnt',
            field=models.JSONField(default=list, help_text='List of feature counts required by users in history'),
        ),
    ]
