# Generated by Django 4.1.3 on 2022-12-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioner', '0003_alter_question_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='model_COM_x',
            field=models.FloatField(help_text='Center of mass (x-axis)', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='model_COM_y',
            field=models.FloatField(help_text='Center of mass (y-axis)', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='model_COM_z',
            field=models.FloatField(help_text='Center of mass (z-axis)', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='model_SA',
            field=models.FloatField(help_text='Surface area', null=True),
        ),
    ]
