# Generated by Django 4.1.3 on 2023-01-23 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questioner', '0003_authuser_end_microversion_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_MPPS',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questioner.question')),
            ],
            bases=('questioner.question',),
        ),
        migrations.RenameField(
            model_name='authuser',
            old_name='curr_question',
            new_name='curr_question_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='completion_feature_cnt',
        ),
        migrations.RemoveField(
            model_name='question',
            name='model_SA',
        ),
        migrations.RemoveField(
            model_name='question',
            name='model_mass',
        ),
        migrations.RemoveField(
            model_name='question',
            name='model_volume',
        ),
        migrations.RemoveField(
            model_name='question',
            name='os_doc_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='os_drawing_element_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='os_drawing_jpeg_element_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='os_part_studio_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='os_workspace_id',
        ),
        migrations.AddField(
            model_name='authuser',
            name='curr_question_type',
            field=models.CharField(choices=[('UNKN', 'Unknown'), ('SPPS', 'Single-part Part Studio'), ('MPPS', 'Multi-part Part Studio')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='authuser',
            name='etype',
            field=models.CharField(choices=[('N/A', 'Not Applicable'), ('partstudios', 'Part Studio'), ('assemblies', 'Assembly')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='did',
            field=models.CharField(default=None, max_length=40, verbose_name='Onshape document ID'),
        ),
        migrations.AddField(
            model_name='question',
            name='eid',
            field=models.CharField(default=None, help_text='The Onshape element ID that the thumbnail image will be taken from. It should capture the expected solution to the question.', max_length=40, verbose_name='Onshape element ID'),
        ),
        migrations.AddField(
            model_name='question',
            name='etype',
            field=models.CharField(choices=[('N/A', 'Not Applicable'), ('partstudios', 'Part Studio'), ('assemblies', 'Assembly')], default='N/A', help_text='The Onshape element type of the element which ID is given for thumbnial image.', max_length=40, verbose_name='Onshape element type'),
        ),
        migrations.AddField(
            model_name='question',
            name='jpeg_drawing_eid',
            field=models.CharField(help_text='Export a drawing as a JPEG to the questions document and input that element ID here. Portrait rather than landscape is preferred.', max_length=40, null=True, unique=True, verbose_name='Onshape element ID of a JPEG export of a drawing'),
        ),
        migrations.AddField(
            model_name='question',
            name='os_drawing_eid',
            field=models.CharField(help_text='Element ID of the Onshape drawing that users can open in a new tab.', max_length=40, null=True, unique=True, verbose_name='Onshape element ID of the main Onshape drawing'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('UNKN', 'Unknown'), ('SPPS', 'Single-part Part Studio'), ('MPPS', 'Multi-part Part Studio')], default='UNKN', max_length=4),
        ),
        migrations.AddField(
            model_name='question',
            name='wid',
            field=models.CharField(default=None, max_length=40, verbose_name='Onshape workspace ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='completion_time',
            field=models.JSONField(default=list, help_text='List of completion time (in seconds) by users in history'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('NA', 'Unclassified'), ('CH', 'Challenging'), ('ME', 'Medium'), ('EA', 'Easy')], default='NA', max_length=2),
        ),
        migrations.CreateModel(
            name='Question_SPPS',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questioner.question')),
                ('completion_feature_cnt', models.JSONField(default=list, help_text='List of feature counts required by users in history')),
                ('model_mass', models.FloatField(help_text='Mass in kg', null=True)),
                ('model_volume', models.FloatField(help_text='Volume in m^3', null=True)),
                ('model_SA', models.FloatField(help_text='Surface area in m^2', null=True)),
            ],
            bases=('questioner.question',),
        ),
    ]
