# Generated by Django 4.1.3 on 2022-12-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioner', '0004_alter_question_model_com_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='additional_instructions',
            field=models.TextField(default=None, help_text='(Opitonal) additional instructions for users', null=True),
        ),
    ]
