# Generated by Django 4.1.3 on 2023-01-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioner', '0004_question_mpps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_spps',
            name='model_inertia',
            field=models.JSONField(help_text='3 element array describing the Principal Interia', null=True),
        ),
    ]
