# Generated by Django 4.1.3 on 2023-01-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioner', '0004_question_mpps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='wid',
        ),
        migrations.AddField(
            model_name='authuser',
            name='add_field',
            field=models.JSONField(default=dict, help_text="An additional field that can be used for some question types to store additional data in the user's model", null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='vid',
            field=models.CharField(default=None, max_length=40, verbose_name='Onshape version ID'),
        ),
        migrations.AddField(
            model_name='question_mpps',
            name='completion_feature_cnt',
            field=models.JSONField(default=list, help_text='List of feature counts required by users in history'),
        ),
        migrations.AddField(
            model_name='question_mpps',
            name='mid',
            field=models.CharField(default=None, help_text="Last microversion of the starting element's version", max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='question_mpps',
            name='model_SA',
            field=models.JSONField(default=list, help_text='Surface area in m^2', null=True),
        ),
        migrations.AddField(
            model_name='question_mpps',
            name='model_mass',
            field=models.JSONField(default=list, help_text='Mass in kg', null=True),
        ),
        migrations.AddField(
            model_name='question_mpps',
            name='model_volume',
            field=models.JSONField(default=list, help_text='Volume in m^3', null=True),
        ),
        migrations.AddField(
            model_name='question_mpps',
            name='starting_eid',
            field=models.CharField(default=None, help_text='(Optional) Starting part studio that need to be imported to user document with derived features. Leave blank if none is required.', max_length=40, null=True),
        ),
    ]
