# Generated by Django 4.2 on 2024-06-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioner', '0005_alter_authuser_completed_history_alter_authuser_did_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='custom_tolerance',
            field=models.DecimalField(decimal_places=4, help_text='Input custom tolerance for challenge (input in decimal percent - default is 0.005)', max_digits=5, null=True, verbose_name='Custom tolerance for challenge (decimal percent - default is 0.005)'),
        ),
    ]
