# Generated by Django 4.2 on 2024-07-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioner', '0006_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Users can only see the certificate after it is published'),
        ),
    ]
