# Generated by Django 4.1.3 on 2023-01-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioner', '0006_alter_question_mpps_starting_eid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authuser',
            old_name='end_microversion_id',
            new_name='end_mid',
        ),
        migrations.RenameField(
            model_name='authuser',
            old_name='start_microversion_id',
            new_name='start_mid',
        ),
        migrations.AddField(
            model_name='question',
            name='allowed_etype',
            field=models.CharField(choices=[('N/A', 'Not Applicable'), ('partstudios', 'Part Studio'), ('assemblies', 'Assembly'), ('all', 'All Types')], default='all', help_text='Allowed Onshape element type(s) that can start this question.', max_length=40, verbose_name='Allowed element type(s)'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='etype',
            field=models.CharField(choices=[('N/A', 'Not Applicable'), ('partstudios', 'Part Studio'), ('assemblies', 'Assembly'), ('all', 'All Types')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='etype',
            field=models.CharField(choices=[('N/A', 'Not Applicable'), ('partstudios', 'Part Studio'), ('assemblies', 'Assembly'), ('all', 'All Types')], default='N/A', help_text='The Onshape element type of the element which ID is given for thumbnial image.', max_length=40, verbose_name='Onshape element type'),
        ),
    ]
