# Generated by Django 4.1.3 on 2023-01-25 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questioner', '0005_question_spps_model_inertia'),
        ('questioner', '0006_alter_question_mpps_starting_eid'),
    ]

    operations = [
    ]
