# Generated by Django 4.1.3 on 2022-12-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioner', '0007_remove_question_model_com_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='cad_drawing',
            field=models.CharField(help_text='Insert single PDF file in GitHub repository and enter file name here (without .pdf suffix)', max_length=200, null=True, unique=True, verbose_name='File name of CAD drawing'),
        ),
    ]
