# Generated by Django 4.2 on 2024-06-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioner', '0007_alter_question_custom_tolerance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='custom_tolerance',
            field=models.FloatField(help_text='Input custom tolerance for challenge (input in decimal percent - default is 0.005)', null=True, verbose_name='Custom tolerance for challenge (decimal percent - default is 0.005)'),
        ),
    ]
