# Generated by Django 4.1.3 on 2023-01-27 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questioner', '0007_rename_end_microversion_id_authuser_end_mid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question_mpps',
            options={'verbose_name': 'Multi-part Part Studio Question'},
        ),
        migrations.AlterModelOptions(
            name='question_spps',
            options={'verbose_name': 'Single-part Part Studio Question'},
        ),
    ]
