# Generated by Django 4.1.3 on 2022-12-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioner', '0008_alter_question_cad_drawing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='additional_instructions',
            field=models.TextField(blank=True, default=None, help_text='(Opitonal) additional instructions for users', null=True),
        ),
    ]
