# Generated by Django 4.2 on 2024-06-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioner', '0008_alter_question_custom_tolerance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='custom_tolerance',
        ),
        migrations.AddField(
            model_name='question_asmb',
            name='err_tolerance',
            field=models.FloatField(blank=True, default=1e-07, help_text='Input custom tolerance for challenge (input in decimal percent - default is 1e-7 for assemblies)', null=True, verbose_name='Custom tolerance for challenge'),
        ),
        migrations.AddField(
            model_name='question_mpps',
            name='err_tolerance',
            field=models.FloatField(blank=True, default=0.005, help_text='Input custom tolerance for challenge (input in decimal percent - default is 0.005 for part studios)', null=True, verbose_name='Custom tolerance for challenge'),
        ),
        migrations.AddField(
            model_name='question_spps',
            name='err_tolerance',
            field=models.FloatField(blank=True, default=0.005, help_text='Input custom tolerance for challenge (input in decimal percent - default is 0.005 for part studios)', null=True, verbose_name='Custom tolerance for challenge'),
        ),
    ]
