# Generated by Django 4.1.3 on 2023-01-30 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questioner', '0007_merge_20230125_2120'),
        ('questioner', '0008_alter_question_mpps_options_and_more'),
    ]

    operations = [
    ]
