# Generated by Django 4.2 on 2024-07-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questioner', '0007_certificate_is_published'),
        ('questioner', '0009_remove_question_custom_tolerance_and_more'),
    ]

    operations = [
    ]
