# Generated by Django 4.1.3 on 2023-02-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioner', '0010_reviewer_rename_modelling_authuser_is_modelling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
