# Generated by Django 4.1.3 on 2023-02-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioner', '0011_reviewer_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question_mpps',
            old_name='mid',
            new_name='init_mid',
        ),
        migrations.AddField(
            model_name='question_mpps',
            name='ref_mid',
            field=models.CharField(default=None, help_text="Last microversion of the reference element's version", max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='question_spps',
            name='ref_mid',
            field=models.CharField(default=None, help_text="Last microversion of the reference element's version", max_length=40, null=True),
        ),
    ]
