# Generated by Django 4.1.3 on 2023-02-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioner', '0012_rename_mid_question_mpps_init_mid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='failure_history',
            field=models.JSONField(default=dict),
        ),
    ]
