# Generated by Django 4.1.3 on 2023-02-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioner', '0013_authuser_failure_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_collecting_data',
            field=models.BooleanField(default=True, help_text='User design data is only collected when this is set to be True'),
        ),
    ]
