# Generated by Django 4.1.3 on 2023-02-20 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questioner', '0014_question_is_collecting_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_ASMB',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questioner.question')),
                ('starting_eid', models.CharField(default=None, help_text='Starting part studio with parts that need to be imported to user assembly to be assembled.', max_length=40, null=True, verbose_name='Source Part Studio element ID')),
                ('completion_feature_cnt', models.JSONField(default=list, help_text='List of mate feature counts required by users in history')),
                ('model_inertia', models.JSONField(default=list, help_text='3 element array describing the Principal Interia', null=True)),
            ],
            options={
                'verbose_name': 'Assembly Mating Question',
            },
            bases=('questioner.question',),
        ),
        migrations.AddField(
            model_name='question_mpps',
            name='model_inertia',
            field=models.JSONField(default=list, help_text='List of 3 element array describing the Principal Interia', null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='curr_question_type',
            field=models.CharField(choices=[('UNKN', 'Unknown'), ('SPPS', 'Single-part Part Studio'), ('MPPS', 'Multi-part Part Studio'), ('ASMB', 'Assembly Mating')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('UNKN', 'Unknown'), ('SPPS', 'Single-part Part Studio'), ('MPPS', 'Multi-part Part Studio'), ('ASMB', 'Assembly Mating')], default='UNKN', max_length=4),
        ),
        migrations.AlterField(
            model_name='question_spps',
            name='model_inertia',
            field=models.JSONField(default=list, help_text='3 element array describing the Principal Interia', null=True),
        ),
    ]
