# Generated by Django 4.1.3 on 2023-02-20 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_user_id', models.CharField(default=None, max_length=30)),
                ('start_time', models.DateTimeField(default=None, null=True)),
                ('time_of_completion', models.DateTimeField(default=None, null=True)),
                ('question_id', models.IntegerField(default=0)),
                ('question_type', models.CharField(choices=[('UNKN', 'Unknown'), ('SPPS', 'Single-part Part Studio'), ('MPPS', 'Multi-part Part Studio'), ('ASMB', 'Assembly Mating')], default='UNKN', max_length=4)),
                ('num_attempt', models.IntegerField(default=0)),
                ('time_spent', models.FloatField(default=0.0)),
                ('is_final_failure', models.BooleanField(default=False)),
                ('microversions_discrip', models.JSONField(default=list, null=True)),
                ('final_query_complete_time', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryData_AS',
            fields=[
                ('historydata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_miner.historydata')),
                ('first_failed_time', models.DateTimeField(default=None, null=True)),
                ('failed_assembly_def', models.JSONField(default=dict, null=True)),
                ('failed_shaded_views', models.JSONField(default=dict, null=True)),
                ('final_assembly_def', models.JSONField(default=dict, null=True)),
                ('final_shaded_views', models.JSONField(default=dict, null=True)),
            ],
            bases=('data_miner.historydata',),
        ),
        migrations.CreateModel(
            name='HistoryData_PS',
            fields=[
                ('historydata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_miner.historydata')),
                ('first_failed_time', models.DateTimeField(default=None, null=True)),
                ('failed_feature_list', models.JSONField(default=dict, null=True)),
                ('failed_shaded_views', models.JSONField(default=dict, null=True)),
                ('failed_mesh', models.TextField(blank=True, default=None, null=True)),
                ('final_feature_list', models.JSONField(default=dict, null=True)),
                ('final_shaded_views', models.JSONField(default=dict, null=True)),
                ('process_mesh', models.JSONField(default=list, null=True)),
            ],
            bases=('data_miner.historydata',),
        ),
    ]
