# Generated by Django 4.1.3 on 2022-12-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_miner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historydata',
            name='query_complete_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
