# Generated by Django 4.1.7 on 2023-03-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_miner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historydata',
            name='question_type',
            field=models.CharField(choices=[('UNKN', 'Unknown'), ('SPPS', 'Single-part Part Studio'), ('MPPS', 'Multi-part Part Studio'), ('ASMB', 'Assembly Mating'), ('MSPS', 'Multi-step Part Studio')], default='UNKN', max_length=4),
        ),
    ]
