# Generated by Django 4.1.3 on 2023-01-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_miner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historydata',
            name='shaded_views',
        ),
        migrations.AddField(
            model_name='historydata',
            name='query_complete_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='historydata',
            name='question_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historydata',
            name='time_spent',
            field=models.FloatField(default=0.0),
        ),
    ]
