# Generated by Django 4.1.3 on 2023-01-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_miner', '0002_historydata_query_complete_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='historydata',
            name='time_spent',
            field=models.FloatField(default=0.0),
        ),
    ]
