# Generated by Django 4.1.7 on 2023-03-20 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_miner', '0002_alter_historydata_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historydata',
            name='time_spent',
        ),
    ]
