# Generated by Django 4.1.3 on 2023-01-27 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_miner', '0002_remove_historydata_shaded_views_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryData_PS',
            fields=[
                ('historydata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_miner.historydata')),
                ('first_failed_time', models.DateTimeField(default=None, null=True)),
                ('failed_feature_list', models.JSONField(default=dict, null=True)),
                ('failed_shaded_views', models.JSONField(default=dict, null=True)),
                ('failed_mesh', models.TextField(blank=True, default=None, null=True)),
                ('final_feature_list', models.JSONField(default=dict, null=True)),
                ('final_shaded_views', models.JSONField(default=dict, null=True)),
                ('process_mesh', models.JSONField(default=list, null=True)),
            ],
            bases=('data_miner.historydata',),
        ),
        migrations.RenameField(
            model_name='historydata',
            old_name='query_complete_time',
            new_name='final_query_complete_time',
        ),
        migrations.RenameField(
            model_name='historydata',
            old_name='microversions',
            new_name='microversions_discrip',
        ),
        migrations.RemoveField(
            model_name='historydata',
            name='completion_time',
        ),
        migrations.RemoveField(
            model_name='historydata',
            name='feature_list',
        ),
        migrations.RemoveField(
            model_name='historydata',
            name='fs_representation',
        ),
        migrations.RemoveField(
            model_name='historydata',
            name='mesh_data',
        ),
        migrations.RemoveField(
            model_name='historydata',
            name='question_name',
        ),
        migrations.AddField(
            model_name='historydata',
            name='question_type',
            field=models.CharField(choices=[('UNKN', 'Unknown'), ('SPPS', 'Single-part Part Studio'), ('MPPS', 'Multi-part Part Studio')], default='UNKN', max_length=4),
        ),
        migrations.AddField(
            model_name='historydata',
            name='start_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='historydata',
            name='time_of_completion',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
