# Generated by Django 4.1.3 on 2023-02-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_miner', '0003_historydata_ps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historydata',
            name='is_final_failure',
            field=models.BooleanField(default=False),
        ),
    ]
