# Generated by Django 4.1.3 on 2023-01-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_miner', '0003_historydata_time_spent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historydata',
            name='shaded_views',
        ),
        migrations.AddField(
            model_name='historydata',
            name='question_id',
            field=models.IntegerField(default=0),
        ),
    ]
