# Generated by Django 4.1.7 on 2023-03-24 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_miner', '0003_remove_historydata_time_spent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historydata',
            old_name='microversions_discrip',
            new_name='microversions_descrip',
        ),
    ]
