# Generated by Django 4.1.7 on 2023-04-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_miner', '0004_rename_microversions_discrip_historydata_microversions_descrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historydata',
            name='final_query_complete_time',
            field=models.DateTimeField(default=None, help_text='Time when all data query API calls were completed', null=True),
        ),
        migrations.AlterField(
            model_name='historydata',
            name='is_final_failure',
            field=models.BooleanField(default=False, help_text='Did final sub fail?'),
        ),
        migrations.AlterField(
            model_name='historydata',
            name='microversions_descrip',
            field=models.JSONField(default=list, help_text='Descriptions of all microversion history events (with user names removed)', null=True),
        ),
        migrations.AlterField(
            model_name='historydata',
            name='num_attempt',
            field=models.IntegerField(default=0, help_text='The n-th attempt'),
        ),
        migrations.AlterField(
            model_name='historydata',
            name='question_id',
            field=models.IntegerField(default=0, help_text='Unique question ID'),
        ),
        migrations.AlterField(
            model_name='historydata',
            name='start_time',
            field=models.DateTimeField(default=None, help_text='Time the question was initiated for the user', null=True),
        ),
        migrations.AlterField(
            model_name='historydata',
            name='time_of_completion',
            field=models.DateTimeField(default=None, help_text='Time of the final submission of the question received, either successful or failed', null=True),
        ),
        migrations.AlterField(
            model_name='historydata_as',
            name='failed_assembly_def',
            field=models.JSONField(default=dict, help_text='Assembly definition of the first failed submission assembly', null=True),
        ),
        migrations.AlterField(
            model_name='historydata_as',
            name='failed_shaded_views',
            field=models.JSONField(default=dict, help_text='Shaded view images of the first failed submission assembly', null=True),
        ),
        migrations.AlterField(
            model_name='historydata_as',
            name='final_assembly_def',
            field=models.JSONField(default=dict, help_text='Assembly definition of the final submitted assembly', null=True),
        ),
        migrations.AlterField(
            model_name='historydata_as',
            name='final_shaded_views',
            field=models.JSONField(default=dict, help_text='Shaded view images of the final submitted assembly', null=True),
        ),
        migrations.AlterField(
            model_name='historydata_as',
            name='first_failed_time',
            field=models.DateTimeField(default=None, help_text='Time of the first failed submission', null=True),
        ),
        migrations.AlterField(
            model_name='historydata_ps',
            name='failed_feature_list',
            field=models.JSONField(default=dict, help_text='Feature list of the first failed submission model', null=True),
        ),
        migrations.AlterField(
            model_name='historydata_ps',
            name='failed_mesh',
            field=models.TextField(blank=True, default=None, help_text='Mesh of the first failed submission model', null=True),
        ),
        migrations.AlterField(
            model_name='historydata_ps',
            name='failed_shaded_views',
            field=models.JSONField(default=dict, help_text='Shaded view images of the first failed submission model', null=True),
        ),
        migrations.AlterField(
            model_name='historydata_ps',
            name='final_feature_list',
            field=models.JSONField(default=dict, help_text='Feature list of the final submitted model', null=True),
        ),
        migrations.AlterField(
            model_name='historydata_ps',
            name='final_shaded_views',
            field=models.JSONField(default=dict, help_text='Shaded view images of the final submitted model', null=True),
        ),
        migrations.AlterField(
            model_name='historydata_ps',
            name='first_failed_time',
            field=models.DateTimeField(default=None, help_text='Time of the first failed submission', null=True),
        ),
        migrations.AlterField(
            model_name='historydata_ps',
            name='process_mesh',
            field=models.JSONField(default=list, help_text='The mesh of the model after every feature of the final submitted model', null=True),
        ),
    ]
