# Generated by Django 4.1.3 on 2023-02-20 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_miner', '0004_historydata_is_final_failure'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryData_AS',
            fields=[
                ('historydata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_miner.historydata')),
                ('first_failed_time', models.DateTimeField(default=None, null=True)),
                ('failed_assembly_def', models.JSONField(default=dict, null=True)),
                ('failed_shaded_views', models.JSONField(default=dict, null=True)),
                ('final_assembly_def', models.JSONField(default=dict, null=True)),
                ('final_shaded_views', models.JSONField(default=dict, null=True)),
            ],
            bases=('data_miner.historydata',),
        ),
        migrations.AlterField(
            model_name='historydata',
            name='question_type',
            field=models.CharField(choices=[('UNKN', 'Unknown'), ('SPPS', 'Single-part Part Studio'), ('MPPS', 'Multi-part Part Studio'), ('ASMB', 'Assembly Mating')], default='UNKN', max_length=4),
        ),
    ]
